apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-broker
  template:
    metadata:
      labels:
        app: resource-broker
    spec:
      serviceAccountName: resource-broker
      containers:
        - name: resource-broker
          image: broker
          args:
            - -kubeconfig=/kubeconfig/kubeconfig
            - -kcp-kubeconfig=/kubeconfig/kubeconfig
            - -compute-kubeconfig=/compute-kubeconfig/kubeconfig
            - -acceptapi=acceptapis
            - -coordination-workspace=root:resource-broker
            - -staging-tree-root=root:resource-broker:staging
            - -verification-tree-root=root:resource-broker:verification
            - -requeue-interval=1s
          volumeMounts:
            - name: kubeconfig
              mountPath: /kubeconfig
              readOnly: true
            - name: compute-kubeconfig
              mountPath: /compute-kubeconfig
              readOnly: true
      volumes:
        - name: kubeconfig
          secret:
            secretName: kcp-kubeconfig
        - name: compute-kubeconfig
          configMap:
            name: compute-kubeconfig
      hostAliases:
        - ip: "10.96.188.4"
          hostnames:
            - "localhost"
            - "portal.localhost"
            - "kcp.localhost"
            - "root.kcp.localhost"
            - "kcp.api.portal.localhost"
            - "nereus.kcp.localhost"
            - "triton.kcp.localhost"
