apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resource-broker-system
resources:
- ../rbac
- namespace.yaml
- deployment.yaml
- compute-kubeconfig.yaml

images:
- name: broker
  newName: ghcr.io/platform-mesh/platform-mesh/resource-broker
  newTag: v0.0.1
