apiVersion: coord.broker.platform-mesh.io/v1alpha1
kind: MigrationConfiguration
metadata:
  name: migrate-object-storage
spec:
  from:
    group: storage.example.io
    version: v1alpha1
    kind: ObjectStorage
  to:
    group: storage.example.io
    version: v1alpha1
    kind: ObjectStorage
  stages:
    - name: copy
      preconditions:
        # TODO need to define the "healthy" status
        - to.status.status == "Available"
      successConditions:
        - has(dump.status.succeeded) && dump.status.succeeded >= 1
      templates:
        dump:
          apiVersion: batch/v1
          kind: Job
          spec:
            backoffLimit: 10
            template:
              spec:
                restartPolicy: OnFailure
                containers:
                  - name: copy
                    # from ./platform/object-storage-migrator
                    image: localhost/object-storage-migrator:latest
                    imagePullPolicy: Never
                    volumeMounts:
                      - name: origin
                        mountPath: /secrets/origin
                        readOnly: true
                      - name: dest
                        mountPath: /secrets/dest
                        readOnly: true
                volumes:
                  - name: origin
                    secret:
                      secretName: from-${from.status.relatedResources.credentials.name}
                  - name: dest
                    secret:
                      secretName: to-${to.status.relatedResources.credentials.name}
