# from https://github.com/opendefensecloud/krop-controller/blob/a98e23a5dfb6c05dbb53dcc75ad9296df7d56a1f/config/kcp/rbac/root-rbac.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krop-controller-root
rules:
  # Enter child workspaces through virtual-workspace endpoints.
  - apiGroups: ["core.kcp.io"]
    resources: ["workspaces/content"]
    verbs: ["access"]
  # Read Workspace objects to resolve workspace paths to logical cluster names.
  - apiGroups: ["tenancy.kcp.io"]
    resources: ["workspaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krop-controller-root
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krop-controller-root
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: "system:serviceaccount:krop-system:krop-controller"
