apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: azure-prod
resources:
  - admin-rbac.yaml
helmCharts:
  - name: krop-controller
    repo: oci://ghcr.io/opendefensecloud/charts
    version: 0.1.0
    releaseName: krop-azure-prod
    namespace: azure-prod
    valuesInline:
      image:
        repository: ghcr.io/ntnn/krop-controller
        tag: hackathon-1
      kcp:
        kubeconfigSecret:
          name: krop-kubeconfig
components:
  - ../hostaliases
